### PR TITLE
Tail and ear animation

### PR DESCRIPTION
**Pull request by davidsemakula**
Fixes https://github.com/noblestreet/animate-svg/issues/1

### CODE REVIEW

**Comment by davidsemakula** [comment]
Ears twitch once currently, with an animation delay of 2 seconds.

**Comment by noblestreet** [comment]
Dear David,
I looked at the result but i have some remarks, its not quite what i had in mind. I'll get back to you tomorrow.
Best regards,

Arnaud

**Comment by davidsemakula** [comment]
Hi Arnaud,
Checkout the latest update and let me know if it's more inline with your vision

**Comment by noblestreet** [comment]
Hi David,
Ok, i like the improvement. I need to discuss it with the client. I will have a reply on monday. Is it possible to speed it up (the movement of the tail)?
All done within 1 sec?

**Comment by noblestreet** [comment]
is it possible to replay the action without a page reload?

**Comment by davidsemakula** [comment]
Hi Arnaud,
Fixed the issues you raised.

**Comment by davidsemakula** [comment]
Hi Arnaud,
Yes, just point me to the issue.

**Pull request merged**
